[feat]: 빌드 고장나는 부분 수정(google-service 제이슨 형식 확인 )

diff --git a/.github/workflows/TestDistribution.yml b/.github/workflows/TestDistribution.yml
--- a/.github/workflows/TestDistribution.yml
+++ b/.github/workflows/TestDistribution.yml
@@ -83,6 +83,16 @@ jobs:
           printf "%s" "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/google-services.json
           cat app/google-services.json
 
+      - name: Check if google-services.json is valid JSON
+        run: |
+          if jq empty app/google-services.json; then
+            echo "Valid JSON"
+          else
+            echo "Invalid JSON"
+            exit 1
+          fi
+
+
       # gradle 관련 숨김파일 생성 step 추가 필요
 
       # 회사 코드에 적용시에는 수정 필요 flovor 관련
